#+TITLE: Tincture

Tincture is a frontend toolkit for ClojureScript that provides several utility
functions, components, and definitions to aid/speed up developing web page visuals.

- [[https://roosta.github.io/tincture/][Documentation]]
- [[http://tincture.roosta.sh][Demo site]]

** Requirements

   Tincture requires at least Clojure 1.9.0 and ClojureScript 1.9.542 due to use of
   [[ https://cljs.github.io/api/cljs.spec.alpha/ ][clojure.spec.alpha]] to validate various input. Tincture's components are built
   with [[https://github.com/reagent-project/reagent][Reagent]] in mind but its just hiccup.

** Usage
** Re-frame and Tincture events
** Development
   Start figwheel main with the development build
   #+BEGIN_SRC sh
     lein fig:build
   #+END_SRC

   Figwheel-main will automatically push cljs changes to the browser. Once Figwheel
   starts up, you should be able to open http://localhost:9500 for the
   development server.

** Testing
   Either run:
   #+BEGIN_SRC sh
   lein fig:test
   #+END_SRC
   
   For a headless test environment using chrome, make sure its
   installed on your system.
   
   You can also start the dev build and navigate to
   http://localhost:9500/figwheel-extra-main/auto-testing to get a
   nice interface while coding that runs the tests on each save.


** Sources
   - [[https://github.com/roosta/tincture/blob/master/resources/gradients.json][gradients.json]] sourced from: https://github.com/Ghosh/uiGradients/
   - [[https://github.com/roosta/tincture/blob/0b90def186907c7f4879b1d5930603fa9bc3d6ef/src/tincture/macros.clj#L13][Gradient macro]] sourced from https://github.com/rm-hull/inkspot
   - [[https://github.com/roosta/tincture/blob/master/src/tincture/grid.cljs][Tincture Grid]] is heavily inspired by [[https://material-ui.com/layout/grid/][Material-ui Grid]]
   - [[https://github.com/roosta/tincture/blob/master/src/tincture/typography.cljs][Tincture Typography]] is heavily inspired by [[https://material-ui.com/style/typography/][Material-ui Typography]]
